### ISSUE TITLE
partial matching of arguments

### ISSUE THREAD

**Issue by edzer** [pat-s/sperrorest#26]
It is in general disrecommended to use partial matching in package code. With `options(warnPartialMatchDollar = TRUE)` I see:
```r
pred <- predict(fit, newdata = maipo, type = "class")

## Warning: partial match of 'split' to 'splits'

res.lda.sp$benchmark$runtime.performance

## Warning in res.lda.sp$benchmark: partial match of 'benchmark' to
## 'benchmarks'
```

**Comment by pat-s** [comment]
@edzer thanks! Will clean this up in the next release. Did not know about this option yet :)
