### ISSUE TITLE
future_lapply(): Please use future_lapply() of the future.apply package

### ISSUE THREAD

**Issue by HenrikBengtsson** [pat-s/sperrorest#44]
Hi, [future 1.7.0](https://cran.r-project.org/package=future) is now on CRAN and I'm now starting the process of deprecating the usage `future::future_lapply()`, which has moved to the [future.apply](https://cran.r-project.org/package=future.apply) package.  Please upgrade your code to use:
```r
importFrom(future.apply, future_lapply)
```
or
```r
future.apply::future_lapply()
```
This should be a straightforward update without any surprise.

In the next release of the future package, `future::future_lapply()` will produce a formal "deprecated" warning and in the release after that it will produce a "defunct" error.

**Comment by pat-s** [comment]
Thanks for the notification @HenrikBengtsson!
